### PR TITLE
Add CFN template for Refactor Spaces services

### PR DESCRIPTION
**Pull request by fabbazon**
- Implemented Custom Resource to update API Gateway routes
 - Creates the services and changes API Gateway routes
 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by fabbazon** [comment]
Initial stab at this. Marked as WIP since I need to still add a 'Deploy' resource.

**Comment by fabbazon** [comment]
Executed testing to verify that the custom resources work as expected.

Tested both empty parameters - with RS deployed with the template in `MonoToMicroRefactorSpaces/MonoToMicroCFRefactorSpaces-foundation.yaml` - and specifying the environment, application and gateway id of a RS created manually.

Tested the services - work as expected in both cases.

Tested removing the stacks - both are successfully removed.

**Review by deki — CHANGES_REQUESTED** [review]
Can we move the two new files MonoToMicroServices.yaml and cr-lambda.js to MonoToMicroRefactorSpaces please?
There are two alternatives of the workshop (with and without AWS Migration Hub Refactor Spaces) and ideally we separate those assets into different folders.

**Comment by fabbazon** [comment]
> Can we move the two new files MonoToMicroServices.yaml and cr-lambda.js to MonoToMicroRefactorSpaces please? There are two alternatives of the workshop (with and without AWS Migration Hub Refactor Spaces) and ideally we separate those assets into different folders.

Done! Also fixed CORS issues by adding the 'OPTIONS' route.

**Comment by deki** [comment]
Thanks for your contribution!

**Pull request merged**
